#!/bin/sh

FREESPACE_LIMIT=10
datapart=$(readlink -f /dev/disk/by-label/resin-data)
datadev=$(lsblk $datapart -n -o PKNAME)

resindataexpander_enabled() {
    # On flasher avoid expanding partition
    if [ -h /dev/disk/by-label/flash-boot ]; then
        echo "[INFO] Flasher detected. Avoiding expand partition mechanism."
        return 1
    fi

    parted /dev/$datadev print fix 2>&1 > /dev/null

    return 0
}

resindataexpander_run() {
    info "resindataexpander: Expand data partition... "
    parted -s /dev/$datadev -- resizepart 16 58724352s
    info "resindataexpander: Finished expanding data partition."

    partprobe
    sync
}
