#!/bin/sh

set -e

path="/opt/tegra-binaries-signed"

mtsbootpack="mce_mts_d15_prod_cr_sigheader.bin.encrypt"
sc7="warmboot_wbheader.bin.encrypt"

# Flash first-stage bootloader to reserved memory
dd if="$path/$mtsbootpack" of=/dev/mmcblk0 bs=512 seek=58724353 count=8191
# Flash warmboot code to reserved memory
dd if="$path/$sc7" of=/dev/mmcblk0 bs=512 seek=58746533 count=12287
